import Head from 'next/head'
//import Image from 'next/image'
import { Inter } from '@next/font/google'
//import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'

interface RowDataPacket{
  sowID: number,
  ClientName: string,
  AmtUSDC: number,
  Currency: string,
  Sponsor: string,
  BudgetURL: string,
  SOWURL: string|null,
  StartDate: any,
  EndDate: any,
  Completed: number,
  ClientID: number,
  ProjectTeamPercent: any
}

function Profile() {
  const [data, setData] = useState<RowDataPacket|null>(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('/api/query')
      .then((res) => {console.log(res);return res.text()})
      .then((data) => {
        // console.log(data)
        setData(data)
        setLoading(false)
      })
  }, [])

  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No profile data</p>



  return (
    <div>
      {JSON.parse(data).map((client:RowDataPacket) => <div>{client.ClientName}</div>)}
    </div>
  )
}


const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  return (
    <>
      <Head>
        <title>BC Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Profile />
      </main>
    </>
  )
}
